version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
          MYSQL_HOST: localhost
          MYSQL_DATABASE: socka
          MYSQL_USER: root
          MYSQL_PASSWORD: 
          MYSQL_ROOT_PASSWORD: 
        ports:
          - "3306:3306"
        expose:
          - 3306
        volumes:
          - /var/lib/mysql
          - ./mysql/migrations:/docker-entrypoint-initdb.d
        restart: unless-stopped
